name: cmdoc

on: push

jobs:
  cmdoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: generate docs
      run: ./mill sclin.cmdoc
    - name: commit + push
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true