name: cmdoc

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '*'
      - run: npm ci
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 20
      - name: build
        run: ./mill sclin.assembly
      - name: generate docs
        run: ./mill sclin.cmdoc
      - name: run examples
        run: node docr.js sclin-docs-gen/Commands.md
      - name: push to wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: sclin-docs-gen
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
