name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
    - name: build
      run: ./mill main.assembly
    - name: upload
      uses: svenstaro/upload-release-action@v2
      with:
        file: out/main/assembly.dest/out.jar
        asset_name: sclin